# Configuration for CRAFTY Model

# Paths and Data # if linux used /mnt/c/Users/byari-m/Desktop/CRAFTY_DATA/CRAFTY-EU-1km_upscaled_16
project_path: 'C:\Users\byari-m\Desktop\CRAFTY_DATA\CRAFTY-EU-1km_upscaled_16' 

scenario: 'ssp126'                            #Scenario identifier
regionalization: false						  # Only works if regional data is available (regional demands and GIS cell specificity).
# CRAFTY Mechanisms
initial_demand_supply_equilibrium: true       # Ensure balanced eco-service supply and demand during initial tick
remove_negative_marginal_utility: false       # Set marginal utility of production to 0 if negative
use_abandonment_threshold: true               # Abandon cell if agent competitiveness falls below threshold
mutate_on_competition_win: false              # Create new agent with mutations if competitor wins competition
mutation_interval: 0.01                       # Interval for mutation in child agent parameters
MostCompetitorAFTProbability: 0.8             # Probability of selecting the highest-utility AFT for cell
averaged_residual_demand_per_cell: false      # Averaged residual demand for each cell

# Neighboring Effects
use_neighbor_priority: true                   # Prioritize AFTs in neighboring cells for land competition
neighbor_priority_probability: 0.95           # Probability of selecting neighbor priority for competition
neighbor_radius: 2                            # Radius defining neighborhood if neighbor effect is enabled

# Competitiveness Process
participating_cells_percentage: 0.02          # Percentage of cells participating in competitiveness process
marginal_utility_calculations_per_tick: 1     # Number of times the marginal utility calculated per tick
land_abandonment_percentage: 0.02             # Percentage of land that can be abandoned per tick

# Output Configuration
generate_csv_files: true                      # Enable CSV file output
output_folder_name: ''                        #if left empty defaults to timestamped folder,project_path\output\scenario\output_folder_name
csv_output_frequency: 10                      # Ticks interval for CSV output of land use and service supply
track_changes: false                          # Enable change tracking in output
export_LOGGER: false
LOGGER_info: false
LOGGER_warn: false
LOGGER_trace: false
